version: '3'
services:
  wordpress:
    image: 'wordpress'
    restart: 'always'
    ports:
      - '${WP_HTTP_PORT}:80'
    environment:
      - 'WORDPRESS_DB_NAME=${DB_NAME}'
      - 'WORDPRESS_DB_USER=${DB_USER}'
      - 'WORDPRESS_DB_PASSWORD=${DB_PASSWORD}'
      - 'WORDPRESS_DB_HOST=mysql'
      - 'WORDPRESS_DEBUG=${WORDPRESS_DEBUG}'
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html'
  mysql:
    build:
      context: ./mysql
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}/mysql:/app'
      - '${MYSQL_PATH}/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    build: './phpmyadmin'
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
