version: '3'
services:
  wordpress:
    build: 
      context: './wordpress'
      args:
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
    restart: 'always'
    ports:
      - '${WP_HTTP_PORT}:80'
    environment:
      - 'WORDPRESS_DB_NAME=${DB_NAME}'
      - 'WORDPRESS_DB_USER=${DB_USER}'
      - 'WORDPRESS_DB_PASSWORD=${DB_PASSWORD}'
      - 'WORDPRESS_DB_HOST=mysql'
      - 'WORDPRESS_DEBUG=${WORDPRESS_DEBUG}'
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html'
  mysql:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
