#User defined
user:
  # php_version:
  #   label:
  #     PHP version
  #   hint:
  #     Select a PHP version from the list above
  #   type:
  #     select
  #   values:
  #     - 5.6
  #     - 5.7
  #     - 7.2
  #     - 8.1
  #   target:
  #     PHP_VERSION

  wp_debug:
    label:
      Enable WordPress debug mode?
    type:
      checkbox
    hint:
      Check to enable WordPress debug mode
    target:
      WORDPRESS_DEBUG
  # mysql_version:
  #   label:
  #     MySQL version
  #   hint:
  #     Select MySQL version
  #   type:
  #     select
  #   values:
  #     - "5.0"
  #     - "7.0"
  #   target:
  #     MYSQL_VERSION

  MariaDB_version:
    label:
      MariaDB version
    hint:
      Select a MariaDB version from the list above
    type:
      select
    values:
      - 10.7
      - 10.6
      - 10.5
    target:
      MARIADB_VERSION

#System defaults

system:
  show_localpath_selector:
    true
  #For collecting and storing DB in .env
  #db/user/password
  db_credentials:
    true
  #Generate public ports for the docker image
  ports:
    http:
      WP_HTTP_PORT
    others:
      - MYSQL_PORT
      - PMA_PORT