name: Wordpress Stack

on:
  schedule:
  - cron:  '30 6 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Wordpress-Mariadb-AMD64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image wordpress latest
      run: docker-compose -f "docker-compose.yml" up -d --build --build-arg USER_ID=1000,GROUP_ID=1000
      env:
          MARIADB_VERSION: latest
          APP_CODE_PATH_HOST: /tmp/wordpress
          DB_NAME: test
          DB_USER:  admin
          DB_PASSWORD:  password
          DB_ROOT_PASSWORD: password
          DATA_PATH_HOST: /tmp/db
          USER_ID: "0"
          GROUP_ID: "0"
    - name: PHP version check
      run : docker exec wordpress_wordpress_1 php -v
    - name: Mysql Driver check
      run: docker exec wordpress_wordpress_1 php -m | grep mysqli
    - name: Web site Test
      run: |
        sleep 50s
        sudo curl -I --http2 http://localhost:44181/
    - name: Verify MariaDB running from host, create Database and show Database
      run: |
        while ! docker exec wordpress_mysql_1 mysqladmin --user=root --password=password --host "mysql" ping --silent &> /dev/null ; do
            echo "Waiting for database connection..."
            sleep 2
        done
    - name: Check MariaDB version
      run:  docker exec wordpress_mysql_1 mysql -uroot -ppassword -e "SHOW VARIABLES LIKE '%version%';"
    - name: Verify MariaDB database from user
      run:  docker exec wordpress_mysql_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
    - name: Create a Database
      run:  docker exec wordpress_mysql_1 mysql -uroot -ppassword -e "CREATE DATABASE deckapp"
    - name: Verify Database create or not
      run:  docker exec wordpress_mysql_1 mysql -uroot -ppassword -e "SHOW DATABASES"
    - name: Destroy Container and file
      run:  |
        docker-compose down
        echo "y" | docker image prune -a
        echo "y" | docker volume prune
        sudo rm -rf /tmp/wordpress
        sudo rm -rf /tmp/db
  # Wordpress-Mariadb-ARM64:
  #   runs-on: self-hosted
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image wordpress latest
  #     run: docker-compose -f "docker-compose.yml" up -d --build
  #     env:
  #         MARIADB_VERSION: latest
  #         APP_CODE_PATH_HOST: /tmp/wordpress
  #         DB_NAME: test
  #         DB_USER:  admin
  #         DB_PASSWORD:  password
  #         DB_ROOT_PASSWORD: password
  #         DATA_PATH_HOST: /tmp/db
  #         USER_ID: 1000
  #         GROUP_ID: 1000
  #   - name: PHP version check
  #     run : docker exec wordpress_wordpress_1 php -v
  #   - name: Mysql Driver check
  #     run: docker exec wordpress_wordpress_1 php -m | grep mysqli
  #   - name: Log check list
  #     run: docker logs wordpress_wordpress_1 
  #   - name: Web site Test
  #     run: |
  #       sleep 30s
  #       curl -i http://localhost:44181/
  #   - name: Verify MariaDB running from host, create Database and show Database
  #     run: |
  #       while ! docker exec wordpress_mysql_1 mysqladmin --user=root --password=password --host "mysql" ping --silent &> /dev/null ; do
  #           echo "Waiting for database connection..."
  #           sleep 2
  #       done
  #   - name: Check MariaDB version
  #     run:  docker exec wordpress_mysql_1 mysql -uroot -ppassword -e "SHOW VARIABLES LIKE '%version%';"
  #   - name: Verify MariaDB database from user
  #     run:  docker exec wordpress_mysql_1 mysql -uadmin -ppassword -e "SHOW DATABASES"
  #   - name: Create a Database
  #     run:  docker exec wordpress_mysql_1 mysql -uroot -ppassword -e "CREATE DATABASE deckapp"
  #   - name: Verify Database create or not
  #     run:  docker exec wordpress_mysql_1 mysql -uroot -ppassword -e "SHOW DATABASES"
  #   - name: Destroy Container 
  #     run: |
  #       docker-compose down
  #       echo "y" | docker image prune -a
  #       echo "y" | docker volume prune
  #       while [ -d /tmp/wordpress ]; do
  #       echo "password" | sudo -S whoami
  #       sudo rm -rf /tmp/wordpress/
  #       done
  #       while [ -d /tmp/db ]; do
  #       echo "password" | sudo -S whoami
  #       sudo rm -rf /tmp/db/
  #       done
        
        

  